server:
  port: 8080
  servlet-path: /api/v1
spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: tgt
  jackson:
    joda-date-time-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    serialization:
      write_dates_as_timestamps : false
endpoints:
  sensitive: false
  info:
    sensitive: false

paypal:
  client:
    id: AZYHUao4NRB_-jSrPdp3fIPIqXDpZYutsEvfOCffHzsO4368OB6LAhPnNmAxB2kYiKWHt4XKl_v68iWn
    secret: EM1Spygr2XI5R4DJXmsyKfli21yFjBZUelI-phzNpkEIgLf4U-TZPM181duk2kn3VP5PbL7s9Lsh436z

#logging:
#  file: payment-partners.log
